# Viewing the Data

In [7]:
import pandas as pd
df_population = pd.read_csv('./Datasets/population.csv')
df_recipe = pd.read_json("./Datasets/US_recipes.json")
df_population.head(10)
df_recipe.head(10)

,0,1,2,3,4,5,6,7,8,9,...,8441,8442,8443,8444,8445,8446,8447,8448,8449,8450
Contient,North America,North America,North America,North America,North America,North America,North America,North America,North America,North America,...,North America,North America,North America,North America,North America,North America,North America,North America,North America,North America
Country_State,US,US,US,US,US,US,US,US,US,US,...,US,US,US,US,US,US,US,US,US,US
cuisine,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,Southern Recipes,...,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes,Amish and Mennonite Recipes
title,Sweet Potato Pie,Fresh Southern Peach Cobbler,Best Fried Green Tomatoes,Best Jambalaya,Authentic Louisiana Red Beans and Rice,Southern Pimento Cheese,Kickin' Collard Greens,Bananas Foster,Chef John's Buttermilk Biscuits,Southern Fried Cabbage,...,Amish Buttermilk Pie,Amish Brown Sugar Pie,Red Pepper and Cabbage Pickle,Moist Herman Coffee Cake,Amish Buttermilk Cake,Amish Chocolate Pudding,Gera's Amish Funny Cake,Quick Banana Nut Cake,Amish Sour Cream Apple Pie,Cherry Amish Friendship Bread Cupcakes with Bu...
URL,https://www.allrecipes.com/recipe/12142/sweet-...,https://www.allrecipes.com/recipe/51535/fresh-...,https://www.allrecipes.com/recipe/16760/best-f...,https://www.allrecipes.com/recipe/31848/jambal...,https://www.allrecipes.com/recipe/58211/authen...,https://www.allrecipes.com/recipe/189930/south...,https://www.allrecipes.com/recipe/51803/kickin...,https://www.allrecipes.com/recipe/24705/banana...,https://www.allrecipes.com/recipe/220943/chef-...,https://www.allrecipes.com/recipe/73833/southe...,...,https://www.allrecipes.com/recipe/283612/amish...,https://www.allrecipes.com/recipe/278338/amish...,https://www.allrecipes.com/recipe/256612/red-p...,https://www.allrecipes.com/recipe/7963/moist-h...,https://www.allrecipes.com/recipe/278340/amish...,https://www.allrecipes.com/recipe/278333/amish...,https://www.allrecipes.com/recipe/139695/geras...,https://www.allrecipes.com/recipe/232881/quick...,https://www.allrecipes.com/recipe/278337/amish...,https://www.allrecipes.com/recipe/218218/cherr...
rating,4.8,4.7,4.7,4.8,4.5,4.8,4.8,4.8,4.7,4.7,...,4.8,None,None,3.7,None,3.3,3.6,3.0,None,4.0
total_time,115,60,20,65,690,15,70,20,35,20,...,80,55,615,0,45,20,55,45,60,70
prep_time,15,20,5,20,25,15,10,5,20,10,...,20,15,45,None,15,5,25,15,15,20
cook_time,100,40,15,45,185,None,60,15,15,10,...,60,40,90,None,30,15,30,30,45,20
description,"Shared from a Southern recipe, this homemade s...",This peach cobbler recipe makes the perfect de...,Fried green tomatoes are a quick and easy way ...,"A spicy jambalaya with chicken, andouille saus...",This easy authentic Louisiana red beans and ri...,Pimento cheese is jazzed up with jalapeño and ...,These easy Southern collard greens are kickin'...,Elegant bananas foster made with bananas cooke...,These homemade buttermilk biscuits are buttery...,Fried cabbage with crispy bacon and onion — de...,...,"Simple, quick, and easy to make, you'll love t...","This brown sugar pie, or ""Tears on Your Pillow...",This multi-generational recipe for pickled cab...,"A sourdough spiced coffee cake, also known as ...",This traditional Amish recipe for buttermilk c...,This Amish grandmother's chocolate pudding rec...,Amish cooking is amazingly simple and incredib...,This Amish banana nut cake is a delightful sna...,It doesn't get easier or more delicious than t...,Pink cherry cupcakes topped with fluffy butter...

# Data Info

In [8]:
df_recipe.info()

<class 'pandas.DataFrame'>
Index: 14 entries, Contient to serves
Columns: 8451 entries, 0 to 8450
dtypes: object(8451)
memory usage: 924.4+ KB

In [9]:
df_recipe.describe()

,0,1,2,3,4,5,6,7,8,9,...,8441,8442,8443,8444,8445,8446,8447,8448,8449,8450
count,14,14,14,14,14,13,14,14,14,14,...,14,13,13,12,13,14,14,14,13,14
unique,14,14,14,14,14,12,14,14,14,13,...,14,13,13,12,13,14,14,14,13,13
top,North America,North America,North America,North America,North America,15,North America,North America,North America,10,...,North America,North America,North America,North America,North America,North America,North America,North America,North America,20
freq,1,1,1,1,1,2,1,1,1,2,...,1,1,1,1,1,1,1,1,1,2