# Countries Project

#### import Libraries

In [2]:
import pandas as pd
import numpy as np

#### import Countries Data

In [3]:
df = pd.read_csv("./Countries.csv")

#### Data-Preprocessing

In [4]:
df.shape

(194, 64)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    str
 1   country_long                             194 non-null    str
 2   currency                                 194 non-null    str
 3   capital_city                             194 non-null    str
 4   region                                   194 non-null    str
 5   continent                                194 non-null    str
 6   demonym                                  194 non-null    str
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    str
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    str
 63  title                                    187 non-null    str
dtypes: float64(48), int64(6), str(10)
memory usage: 97.1 KB

In [6]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [7]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [8]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [14]:
df[df["population"] == df["population"].max()][["country", "capital_city", "population"]]

   country capital_city  population
75   India    New Delhi  1417173173

In [17]:
df[df["population"] == df["population"].min()][["country", "capital_city" , "population"]]

    country capital_city  population
179  Tuvalu     Funafuti       11312

In [23]:
df.nlargest(5, "democracy_score")[["country"]].sort_values(by="country")

         country
46       Denmark
74       Iceland
122  New Zealand
127       Norway
164       Sweden

In [26]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='str')

In [27]:
"region" in df.columns

True

In [28]:
[col for col in df.columns if "region" in col.lower()]

['region']

In [29]:
df["region"].nunique()

22

In [44]:
grp = df.groupby("region").sum()
grp

,country,country_long,currency,capital_city,continent,demonym,latitude,longitude,agricultural_land,forest_area,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
region,,,,,,,,,,,,,,,,,,,,,
Australia and New Zealand,AustraliaNew Zealand,Commonwealth of AustraliaNew Zealand,Australian dollarNew Zealand dollar,CanberraWellington,OceaniaOceania,AustralianNew Zealander,-68.000000,307.000000,3659290.00,1438975.9,...,31103035,88.83080,4182351,26920684,12.00,18.35,Full democracyFull democracy,66.1,Anthony AlbaneseJacinda Ardern,Prime MinisterPrime Minister
Caribbean,Antigua and BarbudaBarbadosCubaDominicaDominic...,Antigua and BarbudaBarbadosRepublic of CubaCom...,East Caribbean dollarBarbados dollarCuban peso...,Saint John'sBridgetownHavanaRoseauSanto Doming...,AmericasAmericasAmericasAmericasAmericasAmeric...,AntiguanBarbadianCubanDominicanDominicanGrenad...,215.216667,-866.833333,112569.40,72086.4,...,39699448,320.50637,11706390,27993058,16.92,28.63,UnknownUnknownAuthoritarianUnknownFlawed democ...,378.5,Gaston BrowneMia MottleyRaúl CastroRoosevelt S...,Prime MinisterPrime MinisterFirst Secretary of...
Central America,BelizeCosta RicaEl SalvadorGuatemalaHondurasMe...,BelizeRepublic of Costa RicaRepublic of El Sal...,Belize dollarCosta Rican colonU.S. dollarGuate...,BelmopanSan JoséSan SalvadorGuatemala CityTegu...,AmericasAmericasAmericasAmericasAmericasAmeric...,BelizeanCosta RicanSalvadoranGuatemalanHondura...,116.583333,-705.416667,1148733.00,880963.3,...,178574337,258.15170,43191457,135382880,22.14,42.13,UnknownFull democracyHybrid regimeHybrid regim...,183.4,Dean BarrowCarlos Alvarado QuesadaNayib Bukele...,Prime MinisterPresidentPresidentPresidentPresi...
Central Asia,KazakhstanKyrgyz RepublicTajikistanTurkmenista...,Republic of KazakhstanKyrgyz RepublicRepublic ...,Kazakh tengeKyrgyz somTajik somoniNew Turkmen ...,AstanaBishkekDushanbeAshgabatTashkent,AsiaAsiaAsiaAsiaAsia,KazakhstaniKirghizTadzhikTurkmenUzbekistani,209.000000,338.000000,2888073.00,130105.2,...,78456929,133.99250,40315722,38141207,7.92,13.71,AuthoritarianHybrid regimeAuthoritarianAuthori...,107.7,Qasym-Zhomart ToqaevMukhammedkalyi AbylgazievE...,PresidentPrime MinisterPresidentPresidentPresi...
Eastern Africa,BurundiComorosDjiboutiEritreaEthiopiaKenyaMada...,Republic of BurundiUnion of the ComorosRepubli...,Burundi francComorian francDjibouti francEritr...,BujumburaMoroniDjiboutiAsmaraAddis AbabaNairob...,AfricaAfricaAfricaAfricaAfricaAfricaAfricaAfri...,BurundianComoranDjiboutiEritreanEthiopianKenya...,-88.783333,667.466667,3055193.50,1901384.8,...,460747528,491.91960,322317526,138430002,35.27,65.25,AuthoritarianAuthoritarianAuthoritarianAuthori...,275.0,Pierre NkurunzizaAzali AssoumaniIsmaïl Omar Gu...,PresidentPresidentPresidentPresidentPrime Mini...
Eastern Asia,ChinaDem. People's Rep. KoreaJapanKoreaMongolia,People's Republic of ChinaDemocratic People's ...,Chinese yuanDemocratic People's Republic of Ko...,BeijingPyongyangTokyoSeoulUlan Bator,AsiaAsiaAsiaAsiaAsia,ChineseNorth KoreanJapaneseSouth KoreanMongolian,194.000000,602.500000,6497910.00,2714028.9,...,1618395888,88.21719,544975219,1073420669,10.38,26.89,AuthoritarianAuthoritarianFlawed democracyFlaw...,173.9,Xi JinpingKim Jong-unYoshihide SugaYoon Suk-ye...,General Secretary of the Communist PartyChairm...
Eastern Europe,BelarusBulgariaCzech RepublicHungaryMoldovaPol...,Republic of BelarusRepublic of BulgariaCzech R...,Belarusian rubelBulgarian levCzech korunaHunga...,MinskSofiaPragueBudapestChișinăuWarsawBuchares...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,BelarusianBulgarianCzechHungarianMoldovanPolis...,495.416667,314.000000,3107594.70,8611171.5,...,281981606,249.56950,83412184,198569422,25.00,59.11,AuthoritarianFlawed democracyFlawed democracyF...,368.9,Alexander LukashenkoBoyko BorisovAndrej BabišV...,PresidentPrime MinisterPrime MinisterPrime Min...
Melanesia,FijiPapua New GuineaSolomon IslandsVanuatu,Republic of FijiThe Independent State of Papua...,Fijian dollarPapua New Guinea kinaSolomon Isla...,SuvaPort MoresbyHoniaraPort Vila,OceaniaOceaniaOceaniaOceania,FijianPapua New GuineanSolomon IslanderNi-Vanuatu,-48.000000,648.000000,18056.00,399610.9,...,12123398,31.27001,9934785,2188613,6.05,11.88,Hybrid regimeFlawed democracyUnknownUnknown,72.0,Frank BainimaramaJames MarapeManasseh Sogavare...,Prime MinisterPrime MinisterPrime MinisterPrim...
Micronesia,KiribatiMarshall IslandsMicronesiaNauruPalau,Republic of KiribatiRepublic of the Marshall I...,Australian dollarU.S. dollarU.S. dollarAustral...,South TarawaMajuroPalikirYarenNgerulmud,OceaniaOceaniaOceaniaOceaniaOceania,I-KiribatiMarshalleseMicronesianNauruanPalauan,24.300000,800.666667,693.00,1164.1,...,317688,36.64644,156200,161488,0.00,0.00,UnknownUnknownUnknownUnknownUnknown,107.3,Taneti MaamauDavid KabuaDavid W. PanueloLionel...,PresidentPresidentPresidentPresidentPresident
Middle Africa,AngolaCameroonCentral African RepublicChadCong...,People's Republic of AngolaRepublic of Cameroo...,Angolan kwanzaCentral African CFA francCentral...,LuandaYaoundéBanguiN'DjamenaBrazzavilleKinshas...,AfricaAfricaAfricaAfricaAfricaAfricaAfricaAfri...,AngolanCameroonianCentral AfricanChadianCongol...,23.500000,169.250000,1969166.60,2948528.2,...,206991062,226.93390,103364487,103626575,16.76,20.36,AuthoritarianAuthoritarianAuthoritarianAuthori...,135.6,João LourençoPaul BiyaFaustin-Archange Touadér...,PresidentPresidentPresidentPresidentPresidentP...
Northern Africa,AlgeriaEgyptLibyaMoroccoSudanTunisia,People's Democratic Republic of AlgeriaArab Re...,Algerian dinarEgyptian poundLibyan dinarMorocc...,AlgiersCairoTripoliRabatKhartoumTunis,AfricaAfricaAfricaAfricaAfricaAfrica,AlgerianEgyptianLibyanMoroccanSudaneseTunisian,161.000000,84.000000,1701986.00,270158.0,...,259393961,132.99341,122865071,136528890,9.99,22.60,AuthoritarianAuthoritarianAuthoritarianHybrid ...,134.2,Abdelmadjid TebbouneAbdel Fattah el-SisiFayez ...,PresidentPresidentPrime MinisterKingLeader of ...
Northern America,CanadaUnited States,CanadaUnited States of America,Canadian dollarU.S. dollar,"OttawaWashington, D.C.",AmericasAmericas,CanadianAmerican,98.000000,-192.000000,4635530.00,6567230.0,...,372217459,59.17710,63482852,308734607,8.02,17.11,Full democracyFlawed democracy,70.3,Justin TrudeauJoe Biden,Prime MinisterPresident
Northern Europe,DenmarkEstoniaFinlandIcelandIrelandLatviaLithu...,Kingdom of DenmarkRepublic of EstoniaRepublic ...,Danish kroneEuroEuroIceland kronaEuroEuroEuroN...,CopenhagenTallinnHelsinkiReykjavíkDublinRigaVi...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,DanishEstonianFinnishIcelanderIrishLatvianLith...,588.000000,108.000000,384215.92,752710.0,...,105905431,369.88740,17769120,88136311,65.19,87.73,Full democracyFlawed democracyFull democracyFu...,366.2,Mette FrederiksenJüri RatasSanna MarinKatrín J...,Prime MinisterPrime MinisterPrime MinisterPrim...
Polynesia,SamoaTongaTuvalu,SamoaKingdom of TongaTuvalu,Samoan talaTongan pa'angaAustralian dollar,ApiaNuku'alofaFunafuti,OceaniaOceaniaOceania,SamoanTonganTuvaluan,-41.583333,-169.333333,862.10,1716.2,...,340552,22.91670,269254,71298,7.36,0.00,UnknownUnknownUnknown,55.6,Tuilaepa Aiono Sailele MalielegaoiPōhiva Tu'i'...,Prime MinisterPrime MinisterPrime Minister
South America,ArgentinaBoliviaBrazilChileColombiaEcuadorGuya...,Argentine RepublicPlurinational State of Boliv...,Argentine pesoBolivian BolivianoBrazilian real...,Buenos AiresSucreBrasíliaSantiagoBogotáQuitoGe...,AmericasAmericasAmericasAmericasAmericasAmeric...,ArgentineBolivianBrazilianChileanColombianEcua...,-138.000000,-775.500000,5305968.50,8361834.0,...,437232783,381.39130,65965026,371267757,33.85,78.92,Flawed democracyHybrid regimeFlawed democracyF...,307.2,Alberto FernándezJeanine ÁñezJair BolsonaroSeb...,PresidentPresidentPresidentPresidentPresidentP...
South-Eastern Asia,BruneiCambodiaIndonesiaLao PDRMalaysiaMyanmarP...,Brunei DarussalamKingdom of CambodiaRepublic o...,Brunei dollarCambodian rielIndonesian rupiahLa...,Bandar Seri BegawanPhnom PenhJakartaVientianeK...,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsia,BruneianCambodianIndonesianLaotianMalaysianBur...,91.700000,1214.716667,1400974.60,2074763.3,...,680786398,245.08821,332532159,348254239,19.15,51.05,UnknownAuthoritarianFlawed democracyAuthoritar...,288.2,Hassanal BolkiahHun SenJoko WidodoBounnhang Vo...,Sultan and Prime MinisterPrime MinisterPreside...
Southern Africa,BotswanaEswatiniLesothoNamibiaSouth Africa,Republic of BotswanaKingdom of EswatiniKingdom...,Botswana pulaSwazi lilangeniLesotho lotiNamibi...,GaboroneLobambaMaseruWindhoekPretoria,AfricaAfricaAfricaAfricaAfrica,MotswanaSwaziMosothoNamibianSouth African,-129.000000,125.000000,1648350.00,394757.8,...,68598688,141.80170,23399685,45199003,14.99,30.97,Flawed democracyAuthoritarianFlawed democracyF...,96.3,Mokgweetsi MasisiMswati IIITom ThabaneHage Gei...,PresidentKingPrime MinisterPresidentPresident
Southern Asia,AfghanistanBangladeshBhutanIndiaIranMaldivesNe...,Islamic State of AfghanistanPeople's Republic ...,Afghan afghaniBangladeshi takaBhutanese ngultr...,KabulDhakaThimphuNew DelhiTehranMaléKathmanduI...,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsia,AfghanBangladeshiBhutaneseIndianIranianMaldiva...,204.750000,683.500000,3184904.00,1005305.9,...,2007898570,149.29324,1252279139,755619431,17.67,39.06,AuthoritarianHybrid regimeHybrid regimeFlawed ...,205.2,Ashraf GhaniSheikh HasinaLotay TsheringNarendr...,PresidentPrime MinisterPrime MinisterPrime Min...
Southern Europe,AlbaniaAndorraBosnia and HerzegovinaCroatiaCyp...,Republic of AlbaniaPrincipality of AndorraBosn...,Albanian lekEuroBosnia and Herzegovina convert...,TiranaAndorra la VellaSarajevoZagrebNicosiaAth...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,AlbanianAndorranBosnianCroatianCypriotGreekIta...,623.050000,214.950000,595680.89,462470.1,...,150711625,484.63300,40619285,110092340,43.85,89.77,Hybrid regimeUnknownHybrid regimeFlawed democr...,576.2,Edi RamaXavier Espot ZamoraValentin InzkoAndre...,Prime MinisterHead of GovernmentHigh Represent...
Western Africa,BeninBurkina FasoCabo VerdeCôte d'IvoireGhanaG...,Republic of BeninBurkina FasoRepublic of Cabo ...,West African CFA francWest African CFA francCa...,Porto-NovoOuagadougouPraiaYamoussoukroAccraCon...,AfricaAfricaAfricaAfricaAfricaAfricaAfricaAfri...,BenineseBurkinabeCape VerdianIvorianGhanaianGu...,190.966667,-106.150000,2814058.50,843766.2,...,429079551,308.45111,219161699,209917852,43.59,75.27,Hybrid regimeHybrid regimeFlawed democracyHybr...,228.2,Patrice TalonRoch Marc Christian KaboréAlassan...,PresidentPresidentPresidentPresidentPresidentP...
Western Asia,ArmeniaAzerbaijanBahrainGeorgiaIraqIsraelJorda...,Republic of ArmeniaRepublic of AzerbaijanKingd...,Armenian dramNew Azeri manatBahraini dinarGeor...,YerevanBakuManamaTbilisiBaghdadJerusalemAmmanK...,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,ArmenianAzerbaijaniBahrainiGeorgianIraqiIsrael...,523.733333,746.333333,2716863.00,300938.4,...,292559508,275.10282,80071865,212487643,30.77,62.97,Hybrid regimeAuthoritarianAuthoritarianHybrid ...,426.1,Nikol PashinyanIlham AliyevSheikh Hamad bin Is...,Prime MinisterPresidentKingPrime MinisterPrime...
Western Europe,AustriaBelgiumFranceGermanyLiechtensteinLuxemb...,Republic of AustriaKingdom of BelgiumFrench Re...,EuroEuroEuroEuroSwiss francEuroEuroEuroSwiss f...,ViennaBrusselsParisBerlinVaduzLuxembourgMonaco...,EuropeEuropeEuropeEuropeEuropeEuropeEuropeEuro...,AustrianBelgianFrenchGermanLiechtensteinerLuxe...,435.416667,65.183333,526162.86,349944.6,...,199926846,332.66380,38873233,161053613,45.76,59.28,Full democracyFlawed democracyFlawed democracy...,356.3,Sebastian KurzSophie WilmèsEmmanuel MacronOlaf...,Federal ChancellorPrime MinisterPresidentFeder...

In [33]:
df["region"].unique()

<StringArray>
[            'Southern Asia',           'Southern Europe',
           'Northern Africa',             'Middle Africa',
                 'Caribbean',             'South America',
              'Western Asia', 'Australia and New Zealand',
            'Western Europe',            'Eastern Europe',
           'Central America',            'Western Africa',
           'Southern Africa',        'South-Eastern Asia',
            'Eastern Africa',          'Northern America',
              'Eastern Asia',           'Northern Europe',
                 'Melanesia',              'Central Asia',
                'Micronesia',                 'Polynesia']
Length: 22, dtype: str

In [34]:
df["region"].value_counts()

region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [39]:
df["region"].value_counts()

region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [41]:
df["region"].value_counts().idxmax()

'Western Asia'

In [42]:
df["region"].value_counts().max()

np.int64(17)

In [43]:
region = df["region"].value_counts().idxmax()
count = df["region"].value_counts().max()

region, count

('Western Asia', np.int64(17))

In [46]:
df[df["region"] == "Eastern Europe"]["country"]

14             Belarus
24            Bulgaria
43      Czech Republic
73             Hungary
111            Moldova
136             Poland
139            Romania
140             Russia
151    Slovak Republic
181            Ukraine
Name: country, dtype: str

In [51]:
len(df[df["region"] == "Eastern Europe"])

10

In [55]:
df[df["region"] == "Eastern Europe"].shape[0]

10

In [53]:
df["region"].value_counts()["Eastern Europe"]

np.int64(10)

In [61]:
df[df["population"] == df["population"].nlargest(2).iloc[1]]["political_leader"]

34    Xi Jinping
Name: political_leader, dtype: str

In [63]:
df[df["country"] == "Pakistan"]["political_leader"]

129    Imran Khan
Name: political_leader, dtype: str

In [65]:
df.loc[df["political_leader"].isna()]["country"]

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: str

In [67]:
df.loc[df["political_leader"].isna()]["country"].count()

np.int64(7)

In [76]:
df[df["country_long"].str.contains("Republic")]["country"]

1        Albania
2        Algeria
4         Angola
6      Argentina
7        Armenia
         ...
187      Vanuatu
189      Vietnam
191        Yemen
192       Zambia
193     Zimbabwe
Name: country, Length: 125, dtype: str

In [90]:
count = 0
def counting(txt):
    global count
    if "republic" in txt.lower():
        count+=1
    return txt

In [91]:
df["country_long"] = df["country_long"].apply(counting)
print(count)

125

In [89]:
df[df["continent"] == "Africa"].nlargest(1, "population")[["country", "country_long", "population"]]

     country                 country_long  population
125  Nigeria  Federal Republic of Nigeria   218541212