# **Pakistani Population Analysis**

**Author:** Hafiz Waseem Ahmed\
**Email:** waseemdevelopment2002@gmail.com \
**Github:** [waseem-development](https://github.com/waseem-development)

## Source
[The data was collected from the following link:](https://www.kaggle.com/datasets/mabdullahsajid/population-of-pakistan-dataset)

## Years of Data
- 2017
- 1998

## Dataset Description
This dataset contains demographic information from the Pakistan Population Census conducted in 2017. It provides detailed population data at various administrative levels within Pakistan, including provinces, divisions, districts, and sub-divisions. The dataset also includes information on urban and rural populations, gender distribution, transgender individuals, sex ratios, population figures from the 1998 census, and annual growth rates.

## Features
- `Province`: The administrative provinces or regions of Pakistan where the census data was collected.
- `Division`: The divisions within each province. Divisions are the second level of administrative divisions in Pakistan.
- `District`: Districts within each division, representing larger administrative units.
- `Sub-Division`: Sub-divisions or tehsils within each district, providing more localized data.
- `Area`: The land area (in square kilometers) of each sub-division.
- `Urban Population 2017`: The population of urban areas within each sub-division for the year 2017.
- `Rural Population 2017`: The population of rural areas within each sub-division for the year 2017.
- `Male Population 2017`: The male population within each sub-division for the year 2017.
- `Female Population 2017`: The female population within each sub-division for the year 2017.
- `Transgender Population 2017`: The population of transgender individuals within each sub-division for the year 2017.
- `Sex Ratio 2017`: The sex ratio, calculated as the number of females per 1000 males, within each sub-division for the year 2017.
- `Population in 1998`: The total population of each sub-division as recorded in the 1998 census.
- `Annual Growth Rate`: The annual growth rate of the population in each sub-division, calculated as the percentage increase from 1998 to 2017.

## Data Source
The data in this dataset was collected from official Pakistan Population Census reports and may include data from various government sources. It is essential to provide proper attribution and reference the original sources when using this dataset for analysis or research.

## Data Usage
Researchers and analysts can use this dataset to explore demographic trends, population growth, urbanization rates, gender distribution, and more within Pakistan at different administrative levels. Ensure compliance with ethical and legal guidelines when using this data for research or public sharing.

> **Note**: This description is a template. Please adapt it based on the actual data sources and specific details of your dataset when creating it for Kaggle or any other platform.

## Purpose of this Analysis
*We will fill this at the end or during process*

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("./datasets/population.csv")

### Data Composition

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROVINCE                    528 non-null    str
 1   DIVISION                    528 non-null    str
 2   DISTRICT                    528 non-null    str
 3   SUB DIVISION                528 non-null    str
 4   AREA (sq.km)                528 non-null    float64
 5   ALL SEXES (RURAL)           528 non-null    int64
 6   MALE (RURAL)                528 non-null    int64
 7   FEMALE (RURAL)              528 non-null    int64
 8   TRANSGENDER (RURAL)         528 non-null    int64
 9   SEX RATIO (RURAL)           528 non-null    float64
 10  AVG HOUSEHOLD SIZE (RURAL)  528 non-null    float64
 11  POPULATION 1998 (RURAL)     528 non-null    int64
 12  ANNUAL GROWTH RATE (RURAL)  528 non-null    float64
 13  ALL SEXES (URBAN)           528 non-null    int64
 14  MALE (URBAN)                528 non-null    int64
 15  FEMALE (URBAN)              528 non-null    int64
 16  TRANSGENDER (URBAN)         528 non-null    int64
 17  SEX RATIO (URBAN)           528 non-null    float64
 18  AVG HOUSEHOLD SIZE (URBAN)  528 non-null    float64
 19  POPULATION 1998 (URBAN)     528 non-null    int64
 20  ANNUAL GROWTH RATE (URBAN)  528 non-null    float64
dtypes: float64(7), int64(10), str(4)
memory usage: 86.8 KB

In [4]:
df.shape

(528, 21)

In [5]:
df.describe()

,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),AVG HOUSEHOLD SIZE (RURAL),POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
count,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000
mean,1492.005871,2.462780e+05,1.252757e+05,1.209841e+05,18.174242,98.982614,6.277064,1.674280e+05,3.124792,1.408635e+05,7.284339e+04,6.799787e+04,22.276515,75.411269,4.406402,8.014457e+04,1.920814
std,2039.453778,2.711898e+05,1.375630e+05,1.337169e+05,25.522248,26.812660,2.074947,1.783890e+05,9.577872,3.512463e+05,1.823492e+05,1.688725e+05,66.068127,49.687341,2.948336,2.023120e+05,2.098908
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,425.000000,5.093450e+04,2.712725e+04,2.397900e+04,1.000000,101.105000,5.700000,3.527350e+04,1.440000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,882.000000,1.652410e+05,8.413450e+04,8.204400e+04,10.000000,105.285000,6.310000,1.172065e+05,2.030000,4.325450e+04,2.198000e+04,2.099900e+04,3.000000,103.195000,5.755000,2.129800e+04,1.855000
75%,1734.250000,3.129112e+05,1.605022e+05,1.522190e+05,25.000000,108.347500,7.200000,2.130542e+05,2.812500,1.178148e+05,6.030175e+04,5.746525e+04,19.000000,107.040000,6.340000,6.542225e+04,2.985000
max,18374.000000,2.297375e+06,1.172995e+06,1.124167e+06,213.000000,139.380000,12.430000,1.044035e+06,100.000000,3.653616e+06,1.905921e+06,1.746900e+06,795.000000,297.810000,10.060000,2.075867e+06,19.780000

In [6]:
df.head()

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48

In [7]:
pd.set_option("display.max_columns", None)